# S Venkatesh Kumar
# Python Programming Assignment 8

1.	Write a Python Program to Add Two Matrices.

In [5]:
import numpy as np
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print('Matrix 1:\n',ar1)
print('Matrix 2:\n',ar2)
print('Matrix 1 + Matrix 2\n',ar1+ar2)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Matrix 1 + Matrix 2
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


2.	Write a Python Program to Multiply Two Matrices.

In [8]:
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print('Matrix 1:\n',ar1)
print('Matrix 2:\n',ar2)
print('Matrix 1 x Matrix 2\n',np.matmul(ar1, ar2))


Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Matrix 1 x Matrix 2
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


3.	Write a Python Program to Transpose a Matrix.

In [10]:
# Transose of a Matrix
print('Matrix before Transpose.\n',ar1)
print('After Transpose\n',np.transpose(ar1))

Matrix before Transpose.
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Transpose
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


4.	Write a Python Program to Sort Words in Alphabetic Order.

In [15]:
# Program to sort words in alphabetical order
n=int(input('Enter how many words?'))
words=[]
for i in range(n):
    a=input(f'{i+1} Enter word:')
    words.append(a)
words.sort()
print('Sorted Words')
for j in words:
    print(j)


Enter how many words?5
1 Enter word:zzzz
2 Enter word:ttttt
3 Enter word:lllll
4 Enter word:aaaaa
5 Enter word:ooooo
Sorted Words
aaaaa
lllll
ooooo
ttttt
zzzz


5.	Write a Python Program to Remove Punctuation From a String.

In [16]:
# Remove punctuation from a string
import string
def punctuation_remove(a):
    for i in string.punctuation:
        a=a.replace(i,'')
    return a
input_str=input('Enter a string with punctuation to remove:')
print('After removing punctuations:',punctuation_remove(input_str))

Enter a string with punctuation to remove:Hello! How are you doing today?
After removing punctuations: Hello How are you doing today
